import { Seeder } from 'typeorm-extension';
import { DataSource } from 'typeorm';
import { KPIAdmin } from '../common/entities/admin/kpi.admin.entity';

export default class CreateKPIs implements Seeder {
  public async run(dataSource: DataSource): Promise<any> {
    await dataSource
      .createQueryBuilder()
      .insert()
      .into(KPIAdmin)
      .values([
        {
          name: 'Conversion',
          description_fr: 'Pourcentage des visiteurs convertis en clients',
          description_en: 'Percentage of visitors converted into customers',
          color: '#3B82F6'
        },
        {
          name: 'Acquisition',
          description_fr: 'Nombre total de nouveaux clients acquis',
          description_en: 'Total number of new customers acquired',
          color: '#10B981'
        },
        {
          name: 'Rétention',
          description_fr: 'Pourcentage de clients conservés sur une période donnée',
          description_en: 'Percentage of customers retained over a given period',
          color: '#F59E0B'
        },
        {
          name: 'Leads',
          description_fr: 'Nombre de prospects générés',
          description_en: 'Number of leads generated',
          color: '#6366F1'
        },
        {
          name: 'Taux d\'abandon',
          description_fr: 'Pourcentage de clients ayant abandonné un processus ou service',
          description_en: 'Percentage of customers who abandoned a process or service',
          color: '#EF4444'
        },
        {
          name: 'Valeur à vie du client (LTV)',
          description_fr: 'Valeur totale générée par un client sur toute la durée de la relation',
          description_en: 'Total value generated by a customer over the lifetime of the relationship',
          color: '#34D399'
        }
      ])
      .execute();
  }
}
